// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szztmhsrsyokegnvvvdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6enRtaHNyc3lva2VnbnZ2dmRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MzU4ODYsImV4cCI6MjA2OTAxMTg4Nn0.l52k15nTpYrik1z6qVg9flqmRc1bbKGnEFVH3-GP8VY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});